# Generated by Django 3.2 on 2021-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('source_name', models.CharField(default='', max_length=100)),
                ('source_website', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
