# Generated by Django 3.2 on 2021-04-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='iso_code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='countries',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='countries',
            name='source_website',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Vaccination_registries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.DateField(db_index=True)),
                ('total_vaccinations', models.IntegerField(blank=True)),
                ('people_vaccinated', models.IntegerField(blank=True)),
                ('people_fully_vaccinated', models.IntegerField(blank=True)),
                ('daily_vaccinations_raw', models.IntegerField(blank=True)),
                ('daily_vaccinations', models.IntegerField(blank=True)),
                ('total_vaccinations_per_hundred', models.FloatField(blank=True)),
                ('people_vaccinated_per_hundred', models.FloatField(blank=True)),
                ('people_fully_vaccinated_per_hundred', models.FloatField(blank=True)),
                ('daily_vaccinations_per_million', models.FloatField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccination_app.countries')),
            ],
        ),
    ]
