# Generated by Django 3.2 on 2021-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0002_auto_20210417_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='iso_code',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='countries',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='countries',
            name='source_website',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
