# Generated by Django 3.2 on 2021-04-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_app', '0003_auto_20210418_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('countries', models.ManyToManyField(to='vaccination_app.Countries')),
            ],
        ),
    ]
